name: Static CI/CD Workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: RUN TESTS
      run: echo "TESTING"


  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: RUN BUILD
      run: echo "BUILDING"


  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy to VM
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        script: |
          cd /var/www/html
          git clone maxoba/stop-watch-app
          sudo systemctl restart nginx
